server:
  port: 9093

service:
  url: 
    updownload: http://localhost:5006 		#数据上传下载服务接口地址
    jiance: http://localhost:8080/jiance  	#站端登录地址

data:
  collect: 
    file: 
      path:  #采集文件存放路径
      name: #当前采集文件名称
      offset:   # 采集文件当前偏移量

jiance:
  errlog:
    path:  #站端错误日志路径
  station:
    name:  #检测站名称
    id:  #检测站编号

#数据采集定时任务启动间隔时间
task:
  corn:
   datacollect: 0 0/5 * * * ?
   platformstatus: 0 0/5 * * * ?