server:
  port: 9092

service:
  url: 
    updownload: http://localhost:5006		#数据上传下载服务接口地址
    jiance: http://localhost:8080/jiance  	#站端登录地址

data:
  collect: 
    file: 
      #采集文件存放路径
      path:  D:/zjUploadJson
      #当前采集文件名称
      name: 
      # 采集文件当前偏移量
      offset: 0

jiance:
  station:
  #检测站名称
    name: 大创精密装备（安微）有限公司
    #检测站编号
    id: 34020101001
  errlog:
  #站端错误日志路径
    path: D:/jiance-logs


#数据采集定时任务启动间隔时间
task:
  corn:
   datacollect: 0/1 * * * * ?
   platformstatus: 0 0/1 * * * ?
   errorlog: 0 0/1 * * * ?